spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: product-service

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
  show-actuator: true
  packages-to-scan: com.ezat.ecommerce
